Esbuild 0.17.x compatibility, bumped package versions, target latest
Kiyozz/electron-esbuild pull request #53
Opened 2023-04-18 01:49 UTC by jonluca

With electron 24 out, and esbuilt 0.17.x having its 17th released, figured I'd update this to work on the latest version

Targets ESNext, Node 19, and uses pnpm 8. Fixes up the watching and incremental logic to work with the new context in esbuilt 0.17.x

2023-04-22 09:10 UTC, Kiyozz requested changes

2023-04-22 09:10 UTC, Kiyozz commented on packages/create-app/package.json
> +    "node": ">=19"
Thanks for your efforts to improve electron-esbuild!

Meanwhile, I don't think the “engines” section should be upgraded. This should indicate which versions of node this package works for.

I’m not into using non-lts versions of node for libraries: please keep it on the minimum version Electron is supporting. This applies for rebuild config of templates too.

2023-04-22 09:10 UTC, Kiyozz commented on packages/create-app/package.json
> +    "prepublishOnly": "ee 'src/**' --format esm --sourcemap --clean-outdir --outdir dist --target node19 --check-types --ts-project tsconfig.types.json",
See my comment for versions.

2023-04-22 09:10 UTC, Kiyozz commented on packages/create-app/templates/main-ts/esbuild.main.config.ts
> +  target: 'node19', // electron version target
See my comments for versions.

2023-04-22 09:10 UTC, Kiyozz commented on packages/create-app/tsconfig.json
> +    "target": "ESNext",
Are you sure about this? Why this change?

2023-04-22 09:10 UTC, Kiyozz commented on packages/ee/package.json
> +    "pnpm": ">=7"
Then, this should be 8 here

2023-04-22 09:10 UTC, Kiyozz commented on packages/electron-esbuild/package.json
> +  "name": "electron-esbuild-17x",
Do not change the package name

2023-04-22 21:35 UTC, jonluca commented
Cool - yeah this was partially wanting to contribute up stream and partially trying to improve performance of my app, so removing polyfills/modernizing build targets made sense. Will remove those changes for the PR though - just updated

2023-04-22 22:45 UTC, Kiyozz requested changes
I finished review the code. When I can, I will test this! 🙂

2023-04-22 22:45 UTC, Kiyozz commented on package.json
> +    "pnpm": ">=8"
```suggestion
    "pnpm": "8"
```

2023-05-25 13:22 UTC, Kiyozz approved these changes

2023-05-25 13:23 UTC, merged

2023-05-25 13:26 UTC, Kiyozz commented
I wanted to take a moment to express my sincere gratitude for your valuable contribution to electron-esbuild. Your recent support and pull-request proposal to fix the bug has been immensely appreciated. Once again, thank you for extending your support to electron-esbuild.